content = (
    'package com.example.helloapp\n\n'
    'import android.os.Bundle\n'
    'import androidx.activity.ComponentActivity\n'
    'import androidx.activity.compose.setContent\n'
    'import androidx.activity.enableEdgeToEdge\n'
    'import androidx.compose.runtime.*\n'
    'import com.example.helloapp.ui.coach.AICoachScreen\n'
    'import com.example.helloapp.ui.home.HomeScreen\n'
    'import com.example.helloapp.ui.settings.SettingsScreen\n'
    'import com.example.helloapp.ui.theme.HelloAppTheme\n'
    'import com.example.helloapp.ui.training.TrainingScreen\n\n'
    'class MainActivity : ComponentActivity() {\n'
    '    override fun onCreate(savedInstanceState: Bundle?) {\n'
    '        super.onCreate(savedInstanceState)\n'
    '        enableEdgeToEdge()\n'
    '        setContent {\n'
    '            HelloAppTheme {\n'
    '                FitnessApp()\n'
    '            }\n'
    '        }\n'
    '    }\n'
    '}\n\n'
    '@Composable\n'
    'fun FitnessApp() {\n'
    '    var selectedNavItem by remember { mutableStateOf(0) }\n'
    '    var showTrainingScreen by remember { mutableStateOf(false) }\n'
    '    var currentExercise by remember { mutableStateOf("") }\n\n'
    '    if (showTrainingScreen) {\n'
    '        TrainingScreen(\n'
    '            exerciseName = currentExercise,\n'
    '            onBack = { showTrainingScreen = false }\n'
    '        )\n'
    '    } else {\n'
    '        when (selectedNavItem) {\n'
    '            0 -> HomeScreen(\n'
    '                selectedNavItem = selectedNavItem,\n'
    '                onNavItemSelected = { selectedNavItem = it },\n'
    '                onStartTraining = { exercise ->\n'
    '                    currentExercise = exercise\n'
    '                    showTrainingScreen = true\n'
    '                }\n'
    '            )\n'
    '            1 -> AICoachScreen(\n'
    '                selectedNavItem = selectedNavItem,\n'
    '                onNavItemSelected = { selectedNavItem = it }\n'
    '            )\n'
    '            2 -> SettingsScreen(\n'
    '                selectedNavItem = selectedNavItem,\n'
    '                onNavItemSelected = { selectedNavItem = it }\n'
    '            )\n'
    '        }\n'
    '    }\n'
    '}\n'
)
path = r'd:\项目\安卓\HelloApp\app\src\main\java\com\example\helloapp\MainActivity.kt'
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('done')

